### ISSUE TITLE
Arpeggios

### ISSUE THREAD

**Issue by 7sharp9** [pedromsantos/vaughan#3]
I was curious if you had any thought regarding adding arpeggios?

<img width="220" alt="screen shot 2018-03-24 at 10 13 13" src="https://user-images.githubusercontent.com/588746/37862954-b86579de-2f4d-11e8-9e06-c4103c970828.png">

Like optimising fingering at a certain position or skipping string etc:

<img width="325" alt="screen shot 2018-03-24 at 10 20 52" src="https://user-images.githubusercontent.com/588746/37862964-dfb417c0-2f4d-11e8-9be7-85ca6cd12c99.png">

**Comment by pedromsantos** [comment]
Thank you for your comment. This is exactly what I'm looking at now :) Been thinking on adding arpeggios to the library for the past weeks.

**Comment by pedromsantos** [comment]
Just pushed a few changes that implement the first version of guitar arpeggios.
