### ISSUE TITLE
Arpeggios would probably want options for min/max string, probably maximum span on one string.

### ISSUE THREAD

**Issue by 7sharp9** [pedromsantos/vaughan#4]
Most of the arpeggios I play have quite a span on the same string if possible, unless Im playing around low lower 7 frets.  C major on the 8th fret for example, I would probably play it like this:
```
e||--------------------8^13--||
B||-----------------8--------||
G||--------------9-----------||
D||-----------10-------------||
A||--------10----------------||
E||---8^13-------------------||
```

The 5 fret spans are fine at that position but not as easy if you are playing the inversion starting on the G at the 3rd fret of the 6th string.

**Comment by pedromsantos** [comment]
Ok, thanks for the feedback, will have a look
